In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score, precision_score, precision_recall_fscore_support

/home/aditya/Tools/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
data_formation = pd.read_csv("data/X_resampled_formation.csv").values
test_data_formation = pd.read_csv("data/X_test_formation.csv").values
label_formation = pd.read_csv("data/y_resampled_formation.csv").idxmax(axis=1).values
test_label_formation = pd.read_csv("data/y_test_formation.csv").idxmax(axis=1).values

# Logistic Regression Model

In [3]:
logistic_reg_clf = LogisticRegression(penalty = 'l2', solver='lbfgs',
                                      multi_class='multinomial').fit(data_formation, label_formation)

In [4]:
validation_acc = logistic_reg_clf.score(test_data_formation, test_label_formation)
print("Validation Accuracy: %f" % (validation_acc))

Validation Accuracy: 0.364241


In [14]:
y_pred = logistic_reg_clf.predict(test_data_formation)
p_score_avg, r_score_avg, f1_score_avg, _ = precision_recall_fscore_support(test_label_formation, y_pred, average='weighted')
print("Averages")
print(p_score_avg)
print(r_score_avg)
print(f1_score_avg)


p_scores, r_scores, f1_scores, _ = precision_recall_fscore_support(test_label_formation, y_pred, average=None)
print("Per Class")
print(p_scores)
print(r_scores)
print(f1_scores)

Averages
0.35561701414403385
0.3642406114988368
0.35939007448535754
Per Class
[0.24701195 0.25138122 0.47519582]
[0.23220974 0.2300885  0.51376147]
[0.23938224 0.24026403 0.49372669]


# Random Forest

In [15]:
random_forest_clf = RandomForestClassifier(n_estimators=50).fit(data_formation, label_formation)

In [16]:
validation_acc = random_forest_clf.score(test_data_formation, test_label_formation)
print("Validation Accuracy: %f" % (validation_acc))

Validation Accuracy: 0.364241


In [17]:
y_pred = random_forest_clf.predict(test_data_formation)
p_score_avg, r_score_avg, f1_score_avg, _ = precision_recall_fscore_support(test_label_formation, y_pred, average='weighted')
print("Averages")
print(p_score_avg)
print(r_score_avg)
print(f1_score_avg)


p_scores, r_scores, f1_scores, _ = precision_recall_fscore_support(test_label_formation, y_pred, average=None)
print("Per Class")
print(p_scores)
print(r_scores)
print(f1_scores)

Averages
0.35395456472118136
0.3642406114988368
0.357203131926634
Per Class
[0.26954492 0.25340136 0.45780051]
[0.28838951 0.18836915 0.50529287]
[0.27864897 0.21609862 0.48037571]
